#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run format:check ||
(
  echo "Prettier check failed😥, Run npm run format, add changes and commit again"
  false;
)

npx lint-staged ||
(
  echo 'eslint check failed😥, try npm run lint:fix or fix it manualy, add changes and commit again'
  false;
)

echo "Alright... Code looks good, Trying to build now"

npm run build ||
(
  echo "Oh s**, build faild, View the errors above to see why"
)
