# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '21 16 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is inactive for long time'
        stale-pr-message: 'This pr is inactive for long time'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
